spring:
  application:
    name: discovery-service
  cloud:
    discovery:
      eureka:
        client:
          fetchRegistry: false
          registerWithEureka: false
        server:
          enableSelfPreservation: false
server:
  port: 8761
